### ISSUE TITLE
android 6 device the App is unfortunately stop

### ISSUE THREAD

**Issue by sumit0606** [liccowee/Google-Cloud-Messaging--Titanium-#45]
it works fine upto android 5 but when i am run the app in android 6 device the App is unfortunately stop and display an error in console log related permission.

 The Error result Log:

[ERROR] :  linker: readlink('/proc/self/fd/20') failed: Permission denied [fd=20]

[ERROR] :  linker: warning: unable to get realpath for the library "/data/app/com.indusnet.insuranceM8-2/lib/arm/libstlport_shared.so". Will use given name.

[ERROR] :  linker: readlink('/proc/self/fd/20') failed: Permission denied [fd=20]

[ERROR] :  linker: warning: unable to get realpath for the library "/data/app/com.indusnet.insuranceM8-2/lib/arm/libkroll-v8.so". Will use given name.

[WARN] :   TiTempFileHelper: (main) [38,38] The external temp directory doesn't exist, skipping cleanup

[WARN] :   V8Object: (KrollRuntimeThread) [43,81] Runtime disposed, cannot set property 'userAgent'

[ERROR] :  linker: readlink('/proc/self/fd/20') failed: Permission denied [fd=20]

[ERROR] :  linker: warning: unable to get realpath for the library "/data/app/com.indusnet.insuranceM8-2/lib/arm/libcom.activate.gcm.so". Will use given name.

[ERROR] :  TiApplication: (KrollRuntimeThread) [70,151] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.indusnet.insuranceM8-2/lib/arm/libcom.activate.gcm.so: has text relocations; Titanium 5.1.2,2015/12/16 19:00,ca822b2

[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.indusnet.insuranceM8-2/lib/arm/libcom.activate.gcm.so: has text relocations

[ERROR] :  TiApplication: at java.lang.Runtime.loadLibrary(Runtime.java:372)

[ERROR] :  TiApplication: at java.lang.System.loadLibrary(System.java:1076)

[ERROR] :  TiApplication: at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)

[ERROR] :  TiApplication: at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)

[ERROR] :  TiApplication: at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)

[ERROR] :  TiApplication: at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)

**Comment by tehg00se** [comment]
Getting the same thing on Nexus 5 device.  Works fine on < 6.0.

There's a fork of this repo that's more current here

https://github.com/ankesh27/Titanium-Android-gcm-push-notification-with-bigpicture
